# Generated by Django 3.0.9 on 2020-08-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_headline', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('where', models.CharField(max_length=100)),
                ('when', models.CharField(max_length=100)),
                ('button_text', models.CharField(max_length=100)),
                ('button_url', models.URLField(max_length=255)),
                ('image_1', models.ImageField(upload_to='about')),
                ('image_2', models.ImageField(upload_to='about')),
            ],
        ),
    ]
