# Generated by Django 3.0.9 on 2020-08-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_contactinquiry_gallery_news_sponsor_teammember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
    ]
