# Generated by Django 3.0.9 on 2020-08-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20200804_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image_2',
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, help_text='Optimal Resolution: 470 by 629', null=True, upload_to='about'),
        ),
    ]
