# Generated by Django 3.0.9 on 2020-08-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('News', 'News'), ('Notices', 'Notices'), ('Events', 'Events')], max_length=50),
        ),
    ]
