# Generated by Django 3.0.9 on 2021-01-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20210107_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='video_button_text',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='about',
            name='video_button_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
