# Generated by Django 3.0.9 on 2021-01-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20210107_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinquiry',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='mobile',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='subject',
            field=models.CharField(default='', max_length=255),
        ),
    ]
