# Generated by Django 3.0.9 on 2021-01-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
