# Generated by Django 3.0.9 on 2021-01-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcemanagement', '0002_application_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='institution',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='application',
            name='employment_type',
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='application',
            name='mobile',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='application',
            name='queries',
            field=models.TextField(default=''),
        ),
    ]
